import { FooterNav, Navbar} from "../components/Navigation";
import "./globals.css";




export const metadata = {
  title: "Online Sleep Doctors",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      
      <body>

        <Navbar/>
        {children}
        <FooterNav/>
        
      </body>
    </html>
  );
}
