import { FooterNav, Navbar} from "../components/Navigation";
import "./globals.css";
import localFont from "next/font/local";

const openSans = localFont({src: "../fonts/OpenSans.ttf"});

export const metadata = {
  title: "Online Sleep Doctors",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">

      
      <body className={openSans.className}>

        <Navbar/>
        {children}
        <FooterNav/>
        
      </body>
    </html>
  );
}
