import { FooterNav, Navbar} from "../components/Navigation";
import "./globals.css";




export const metadata = {
  title: "Online Sleep Doctors",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet"/>
      </head>
      
      <body>

        
        
        <Navbar/>
        {children}
        <FooterNav/>
        
      </body>
    </html>
  );
}
